[project]
name = "limi-backend"
version = "0.1.0"
description = ""
authors = [
    {name = "enderdreams", email = "enderdreams@outlook.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0" 

dependencies = [
    "fastapi",
    "uvicorn[standard]",
    "PyPDF2",
    "python-dotenv",
    "langchain",
    "langchain-community (>=0.3.27,<0.4.0)",
    "langchain-google-genai (>=2.1.8,<3.0.0)",
    "python-multipart (>=0.0.20,<0.0.21)",
    "gdown (>=5.1.0,<6.0.0)",
    "requests (>=2.32.4,<3.0.0)",
    "supabase (>=2.0.0,<3.0.0)",
    "psycopg2-binary (>=2.9.0,<3.0.0)",
    "pgvector (>=0.2.0,<1.0.0)",
    "sqlalchemy (>=2.0.0,<3.0.0)",
    "numpy (>=2.3.2,<3.0.0)",
]

[tool.poetry]
packages = [{include = "src_limi", from = "."}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
